### ISSUE TITLE
Malformed targa image file causes integer divide by zero in lt-cjpeg (SIGFPE)

### ISSUE THREAD

**Issue by geeknik** [cloudflare/jpegtran#4]
While fuzzing jpegtran with American Fuzzy Lop, I was able to cause a SIGFPE in lt-cjpeg with a malformed targa image file.

~/jpegtran/.libs/lt-cjpeg -targa -optimize -nosmooth -rgb1 test00.tga

```
==42641== Process terminating with default action of signal 8 (SIGFPE)
==42641==  Integer divide by zero at address 0x80335CA1C
==42641==    at 0x4F2B76B: alloc_sarray (jmemmgr.c:399)
==42641==    by 0x40C737: start_input_tga (rdtarga.c:437)
==42641==    by 0x401A24: main (cjpeg.c:626)
Floating point exception

Program received signal SIGFPE, Arithmetic exception.
0x00007ffff7bca76f in alloc_sarray ()
   from /home/geeknik/jpegtran/.libs/libjpeg.so.9
(gdb) bt
#0  0x00007ffff7bca76f in alloc_sarray ()
   from /home/geeknik/jpegtran/.libs/libjpeg.so.9
#1  0x000000000040c738 in start_input_tga ()
#2  0x0000000000401a25 in main () at cjpeg.c:626
(gdb) i r
rax            0x3b9ac9e8	999999976
rbx            0x61a010	6397968
rcx            0x1	1
rdx            0x0	0
rsi            0x1	1
rdi            0x7fffffffdff0	140737488347120
rbp            0x7fffffffdff0	0x7fffffffdff0
rsp            0x7fffffffde60	0x7fffffffde60
r8             0x30	48
r9             0x0	0
r10            0x7fffffffdf40	140737488346944
r11            0x7fffffffdf40	140737488346944
r12            0x7fffffffdff0	140737488347120
r13            0x30	48
r14            0x0	0
r15            0x0	0
rip            0x7ffff7bca76f	0x7ffff7bca76f <alloc_sarray+111>
eflags         0x10246	[ PF ZF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
```

Crashing test case: https://dl.dropboxusercontent.com/u/6088006/test00.tga

**Comment by geeknik** [comment]
FYI, you can rename the above test00.tga to test00.jpg and use a command line like the following to cause the exact same crash:

~/jpegtran/.libs/lt-cjpeg -dct fast -nosmooth -arithmetic -outfile /dev/null -rgb test00.jpg
~/jpegtran/.libs/lt-cjpeg -dct float -outfile /dev/null -grayscale test00.jpg

==47907== Process terminating with default action of signal 8 (SIGFPE)
==47907==  Integer divide by zero at address 0x80335DC6C
==47907==    at 0x4F2B76B: alloc_sarray (jmemmgr.c:399)
==47907==    by 0x40C737: start_input_tga (rdtarga.c:437)
==47907==    by 0x401A24: main (cjpeg.c:626)
Floating point exception
